### ISSUE TITLE
[Dashboard frontend] production dashboard on Redash

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/mobile-test-eng#148]
Adding here the link to the Production Dashboard: 
https://sql.telemetry.mozilla.org/dashboard/mobile-test-eng_1

**Comment by isabelrios** [comment]
To start with I added the two pie charts, for Firefox-iOS and Fenix, related to test automation coverage from Testrail.
But before adding more info, we should decide the format of this production dashboard. It will probably change as we add more data, but at least to have a format to start with and add more graphs.

At the very bottom of the [Staging dashboard](https://sql.telemetry.mozilla.org/dashboard/tests-found-by-automation) I have added two Production Dashboard version. Please leave your feedback here so that we all agree on how to show the info.

Also leaving here the link to the [Perf Sheriff Newsletter ](https://sql.telemetry.mozilla.org/dashboard/perf-sheriff-newsletter?p_framework=%5B%22build_metrics%22%2C%22raptor%22%2C%22awsy%22%2C%22browsertime%22%2C%22talos%22%2C%22js-bench%22%5D&p_range=2020-10-01--2020-10-31)dashboard to have as an example.

I like the idea they show at the top: 
![Captura de pantalla 2021-04-21 a las 12 50 11](https://user-images.githubusercontent.com/1897507/115547520-a2879f00-a2a6-11eb-8120-1324f5280e45.png)

Maybe not in that format, but showing the data sources somehow would be nice
