### ISSUE TITLE
Run Focus Android automated UI tests to verify they are working

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#153]
Also, determine status of tests + test CI.  Do these work the same as Fenix? (re: github events)? and report back to team.  What would be involved with adding new tests, etc.

**Comment by AaronMT** [comment]
Preliminary
* Re-clone Focus Android
* Set up new Android emulator
* Re-run suite locally
* Post results here
* Check on CI hooks, post here

**Comment by AaronMT** [comment]
Build: 7e4034cd (master)

* Pixel 4 (API 30)
* Results [exported Android Studio HTML *.zip](https://github.com/mozilla-mobile/mobile-test-eng/files/5630852/Test.Results.-.Tests_in_.org_mozilla_focus_activity.html.zip)

**Tests in 'org.mozilla.focus.activity': 33 total, 9 error, 15 ignored, 9 passed**

Errors:

- org.mozilla.focus.activity.AddToHomescreenTest
-- SearchTermShortcutTest
- org.mozilla.focus.activity.EraseAllUserDataTest
-- TrashTest
-- systemBarHomeViewTest
-- systemBarTest
- org.mozilla.focus.activity.OpenInExternalBrowserDialogueTest
-- OpenInExternalBrowserDialogueTest
- org.mozilla.focus.activity.SettingsBlockToggleTest
-- SettingsToggleTest
- org.mozilla.focus.activity.ToggleBlockTest
-- SimpleToggleTest
- org.mozilla.focus.activity.URLExceptionTest
-- removeAllExceptionsTest
-- AddAndRemoveExceptionsTest

8/9 fail with

```Java
junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at org.mozilla.focus.helpers.TestHelper.waitForWebContent(TestHelper.java:61)
at org.mozilla.focus.activity.URLExceptionTest.addException(URLExceptionTest.java:134)
```

The UI tests in https://github.com/mozilla-mobile/focus-android/tree/master/app/src/androidTest/java/org/mozilla/focus are flaky. One big source is the use of ``waitFor*`` family of method on the UIAutomator objects with a relatively small timeout (4 seconds). On a machine that is not dedicated to only run the UI tests, these tests can occasionally fail as I've already observed due to the required processing not done within timeout. The current behavior of timing out during waiting is to continue the execution as usual. This causes the test failure message might not directly show the latency of processing being the cause of failure, making debugging difficult.

**Comment by AaronMT** [comment]
Firebase Test Lab: https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab (app Firefox Focus?

The last run was from 8/20/19?

Push to branch schedule is triggered https://github.com/mozilla-mobile/focus-android/blob/master/.taskcluster.yml#L102 which sets up a firebase run https://github.com/mozilla-mobile/focus-android/blob/master/tools/taskcluster/schedule-master-build.py#L98

Example task (Unscheduled?): https://firefox-ci-tc.services.mozilla.com/tasks/ARGa5muRSnSz4iEpkZ_Zfw

Payload definition: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/ARGa5muRSnSz4iEpkZ_Zfw

I believe because [Code Quality] has been failing for a long time, the UI tests are not actually ever ran on CI as the task is only satisfied to be scheduled when dependencies are met and one of the dependencies is (Focus for Android) Code Quality: https://firefox-ci-tc.services.mozilla.com/tasks/MwxY2LjeQWaFB_B-ya1llw.

**Comment by AaronMT** [comment]
Code Quality Failure: https://firefox-ci-tc.services.mozilla.com/tasks/OohJuDmMT-iQ9rYdBo99NA/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FOohJuDmMT-iQ9rYdBo99NA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

```Log
<======-------> 50% CONFIGURING [37s]> :app<=============> 100% CONFIGURING [37s]
FAILURE: Build failed with an exception.
* What went wrong:
Task 'pmd' not found in root project 'focus-android'.
```

Filed as issue: https://github.com/mozilla-mobile/focus-android/issues/4665
