### ISSUE TITLE
Bugzilla 1619060: Intermittent fenix ui-test-x86 [taskcluster:error] Task timeout after 7200 seconds. Force killing container.

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#21]
failure to communicate w/ Firebase API.  see:
https://bugzilla.mozilla.org/show_bug.cgi?id=1619060

**Comment by rpappalax** [comment]
@AaronMT is there anything we want to do with this?  If we'd like to put some kind of monitoring in place, we should ideally create an issue that describes what we'd like to accomplish. It's good that we filed this issue, but we probably should create issues going forward that describe the end result we're looking for (or a fix)

**Comment by AaronMT** [comment]
Flank has requested receiving better support from a gRPC API to resolve endpoint failures. In the event of FTL timing out, Flank can expose that error to us and we can end fast and early. I havn't seen an instance of this particular failure since filing. Unless we want to implement some kind of safety net in the meantime, I think we can wait for Flank for now.
