### ISSUE TITLE
[Smoke tests on release(s)]

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mobile-test-eng#285]
Ticket open to track work to add tests to both Nightly and Beta builds

**Comment by sv-ohorvath** [comment]
As we don't want to start with a big list, these are some that I find to be important, let's discuss it and select only what we really want:
I left out the Download tests area since they had some issues in the past, but since they are fixed now, we can talk about including them if necessary.

- SmokeTest#openMainMenuSettingsItemTest
- SettingsBasicsTest#settingsMenuBasicsItemsTests
- SettingsBasicsTest#selectNewDefaultSearchEngine
- SmokeTest#verifyBasicNavigationToolbarFunctionality
- SmokeTest#verifySearchEngineCanBeChangedTemporarilyUsingShortcuts
- SmokeTest#toggleSearchSuggestions
- SmokeTest#openMainMenuHistoryItemTest
- SmokeTest#noHistoryInPrivateBrowsingTest
- HistoryTest#visitedUrlHistoryTest
- SmokeTest#openMainMenuBookmarksItemTest
- BookmarksTest#addBookmarkTest  (currently disabled for menu redesign but can be fixed if needed)
- SmokeTest#deleteCollectionTest
- SmokeTest#redirectToAppPermissionsSystemSettingsTest
- StrictEnhancedTrackingProtectionTest#testStrictVisitContentNotification
- SettingsPrivacyTest#settingsPrivacyItemsTest 
- SettingsPrivacyTest#loginsAndPasswordsTest or SettingsPrivacyTest#saveLoginFromPromptTest (last failure in Sept.2020)
- HomeScreenTest#homeScreenItemsTest
- HomeScreenTest#privateModeScreenItemsTest
- SettingsAddonsTest#installAddonFromThreeDotMenu
- NoNetworkAccessStartupTests - not running for a long time to know if stable enough, but they are simple enough not to worry

**Comment by isabelrios** [comment]
After talking with Oana we have selected these tests to start with: 

- noNetworkConnectionStartupTest
- SmokeTest#openMainMenuSettingsItemTestHistoryTest#visitedUrlHistoryTest 
- SmokeTest#toggleSearchSuggestions  
- SmokeTest#deleteCollectionTest 
- SmokeTest#noHistoryInPrivateBrowsingTest

**Comment by sv-ohorvath** [comment]
Tests added to Nightly: mozilla-mobile/fenix#18486
Tests added to Beta: mozilla-mobile/fenix#18840
Closing this as done.
