### ISSUE TITLE
[Sync Test Infra] Fenix UI test failure in checkAccountSettings

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/mobile-test-eng#306]
https://github.com/mozilla-mobile/fenix/issues/18631

**Comment by isabelrios** [comment]
Some news on this, I tried to run the test locally and yeah as we guessed the issue is that we don't wait enough to have the FxA page loaded to type the email... 
I tried adding `Thread.sleep(5000)` after this line https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/syncintegration/SyncIntegrationTest.kt#L237 and it worked.

You can try by running directly the test from android studio using this email and password:
(email='pytest-94453165c3@restmail.net', password='iHQukfUT')
Just change lines https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/syncintegration/SyncIntegrationTest.kt#L185 and https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/syncintegration/SyncIntegrationTest.kt#L199 accordingly.

I know the sleep is not the option but knowing where/what the issue is we can find a way to wait before trying to type the email...

**Comment by rpappalax** [comment]
see notes in issues/#301

**Comment by isabelrios** [comment]
Hey @AaronMT, @rpappalax , some updates on this issue... While I was checking a PR that added changes to sync int tests related code, I tried them locally and this test works as it is the first time I run it! 

I would say to close this issue for now and focus on the current errors that prevent us from having these running. Which, for what I have seen, is that the emulator can go offline/online after each test, that causes a lot of issues. We should try to find a way to run all the tests in a row without having to switch it off/on. Or if that's neeed, find a better way. When I implemented this I followed iOS workflow but it may be a better one for android.
