### ISSUE TITLE
Jenkins job to run Sync Int Tests on the update-cartfile-new-as-tag-v* branch

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mobile-test-eng#400]
The idea of this issue is not only to have a general feedback about Smoketest but also a result of the sync int tests and have more info before merging the PR

**Comment by AaronMT** [comment]
Happy to take this. I think because the branches take the name with a version in them we'll have to get the newest branch to run against automatically through some pre command and then using that as the branch somehow (?) (maybe there's an easier way to do this 

https://api.github.com/repos/mozilla-mobile/firefox-ios/branches?per_page=100
`[.[] | select(.name | contains("update-cartfile-new-as-tag-"))][-1]`

```Json
{
  "name": "update-cartfile-new-as-tag-v79.0.0",
  "commit": {
    "sha": "fd546a2e99d4520375defaa8a306617aa489ab5a",
    "url": "https://api.github.com/repos/mozilla-mobile/firefox-ios/commits/fd546a2e99d4520375defaa8a306617aa489ab5a"
  },
  "protected": false
}
```

`.name`
"update-cartfile-new-as-tag-v79.0.0"

Also do want this job on the Intel or M1 machine?

**Comment by isabelrios** [comment]
Thanks for picking this up!
I was thinking about a cron job in Jenkins that scans for an `update-cartfile-new-as-tag-*` branch and if that exists, then start the process to run the tests...
Or an automatic scan to detect when a branch with that name is created.. not sure if that possible...

What I'm almost sure if that jenkins accepts the * card for a branch name

**Comment by AaronMT** [comment]
This is now running on the Intel MacStadium machine. It currently just checks daily for the latest AS release branch opened. I think any improvements we can open as a new issue.
