### ISSUE TITLE
Move xcodereleases RSS feed code to mozilla-mobile github org

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#426]
Check in with Peter if this was done

**Comment by pdehaan** [comment]
You talkin' about https://github.com/pdehaan/xcodereleases-serverless-rss (which was my hacky attempt at a serverless function to convert https://xcodereleases.com/data.json into an [RSS feed](https://xcodereleases-serverless-rss-pdehaan.vercel.app/api/json-to-rss)?

I also DMed the gang at https://twitter.com/xcodereleases asking about an official RSS feed so we can subscribe directly instead of via some proxy service. I'll update here when/if I hear back. ❤️

**Comment by pdehaan** [comment]
Google to the rescue! Possibly https://github.com/xcodereleases/xcodereleases.com/blob/master/api/index.md has the answers ye seek!

## RSS
### All Releases
URL: https://xcodereleases.com/api/all.rss
Description: An RSS feed of all known Xcode releases, including betas. Information about each release is in the `<description>` of each entry.

### GM Releases
URL: https://xcodereleases.com/api/gm.rss
Like [all.rss](https://xcodereleases.com/api/all.rss), but it does not contain any beta, seed, or preview releases. It only contains GM release information.

**Comment by AaronMT** [comment]
Now done, thanks!

**Comment by pdehaan** [comment]
Per discussion w/ @AaronMT this morning, it seems like we currently have these alerts in #ios-eng / #test-infra-alerts / #firefox-ios Slack channels, and they're already set up to use the official https://xcodereleases.com/api/all.rss RSS feed.

So I think we can close this issue since we aren't using my hacky JSON=>RSS converter code (and therefore no need to migrate it into GitHub since it's unused).
