### ISSUE TITLE
iOS ramp-up for team

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#57]
https://docs.google.com/document/d/10nE2DeNK76NgA6S0Hr6Z1l90ic4XHtcg_s4wr36C56E/edit

**Comment by isabelrios** [comment]
Let's add here info that could be useful:
-https://github.com/mozilla-mobile/firefox-ios/wiki/Writing-a-first-XCUI-test-from-the-scratch
-https://github.com/mozilla-mobile/firefox-ios/wiki/Automated-UI-Tests
-https://github.com/mozilla-mobile/firefox-ios/wiki/FxScreenGraph-and-XCUITest
-https://github.com/mozilla-mobile/firefox-ios/wiki/Bitrise-General-Info
-https://github.com/mozilla-mobile/firefox-ios/wiki/Screenshots-for-Localization
-Video demoing screenshots tests environment by Johan: https://mozilla.zoom.us/rec/play/78Akcumoqm03GIKRtQSDU_R6W426K6-sgyEZ_6AOzUjkVyRQNVCkMuMUZOaNt373jb4yUZM4OjfmIJ1U 
-General info about sync int tests: https://docs.google.com/document/d/1iT20UWwm35a7zDoDtUB1msGdEjaXyHHUvuowobVHmfY/edit?usp=sharing

To monitor the issues: 
-Master tab: https://docs.google.com/spreadsheets/d/1OzCuweqTKkKrsgSh2nzuB4-yNcwOrC4667i61pMGCBY/edit?usp=sharing 
-Smoketest, BB results tab: https://docs.google.com/spreadsheets/d/1Zm4DzAUdY7uL0SLho_39-zUPey2Z-nhIglMAf3kQ9Dg/edit#gid=889994167

There are two docs because the Smoketest is aligned with Test Rail Smoketest and it was shared with SV team to keep it update both ways. This can be improvedm for sure...currently I'm the only one checking it to monitor the intermittent but open to do this in a different way.
